In [1]:
import numpy as np
from numpy import genfromtxt

In [2]:
data = genfromtxt('Computer-Vision-with-Python/DATA/bank_note_data.txt',delimiter=',')

In [3]:
# last column has binary values 0 - FORGERY | 1 - AUTHENTIC 
data


array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [4]:
# lets this last "class" column
labels = data[:,4]

In [5]:
y = labels
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [6]:
# and we can also fetch the variables or features
features = data[:,0:4]

In [7]:
X = features
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [8]:
from sklearn.model_selection import train_test_split
# with this function we can separate our train and test groups of data

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33, random_state=42)
# lets take a look at the len(X_train)
len(X_train)

919

In [10]:
# and the len(X_test)
len(X_test)

453

In [11]:
from sklearn.preprocessing import MinMaxScaler
# we will use this function to normalize the value at a certain range. If we have features of different scales of magnitude it will be convenient for a machine learning algorithm to have their features normalized

In [12]:
# we create a scaler object
scaler_object = MinMaxScaler()
# fit it to our training data
scaler_object.fit(X_train)


MinMaxScaler()

In [13]:
# we save the scaled version
scaled_X_train = scaler_object.transform(X_train)

In [14]:
# we apply it also with the test data
scaled_X_test = scaler_object.transform(X_test)


In [15]:
# lets import keras now that our data has been cleaned
from keras.models import Sequential
from keras.layers import Dense

In [16]:
# initialize the neural network
model = Sequential()
# And we add our layer of neurons or 'perceptrons'
model.add(Dense(4,input_dim=4, activation = 'relu'))
# Another layer in the middle
model.add(Dense(8,activation = 'relu'))
# The last layer with sigmoid activation | the sigmoid function will ensure the output is from 0 to 1
model.add(Dense(1,activation = 'sigmoid'))

In [17]:
# now to compile the model

model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [18]:
# now we fit (Train) the modol
model.fit(scaled_X_train,y_train,epochs=50,verbose=2)


Epoch 1/50
29/29 - 1s - loss: 0.7226 - accuracy: 0.4505 - 738ms/epoch - 25ms/step
Epoch 2/50
29/29 - 0s - loss: 0.7070 - accuracy: 0.4505 - 53ms/epoch - 2ms/step
Epoch 3/50
29/29 - 0s - loss: 0.6949 - accuracy: 0.4026 - 53ms/epoch - 2ms/step
Epoch 4/50
29/29 - 0s - loss: 0.6829 - accuracy: 0.4875 - 49ms/epoch - 2ms/step
Epoch 5/50
29/29 - 0s - loss: 0.6715 - accuracy: 0.6692 - 53ms/epoch - 2ms/step
Epoch 6/50
29/29 - 0s - loss: 0.6610 - accuracy: 0.7095 - 56ms/epoch - 2ms/step
Epoch 7/50
29/29 - 0s - loss: 0.6528 - accuracy: 0.7345 - 77ms/epoch - 3ms/step
Epoch 8/50
29/29 - 0s - loss: 0.6445 - accuracy: 0.7399 - 61ms/epoch - 2ms/step
Epoch 9/50
29/29 - 0s - loss: 0.6355 - accuracy: 0.7399 - 54ms/epoch - 2ms/step
Epoch 10/50
29/29 - 0s - loss: 0.6263 - accuracy: 0.7606 - 53ms/epoch - 2ms/step
Epoch 11/50
29/29 - 0s - loss: 0.6167 - accuracy: 0.7639 - 58ms/epoch - 2ms/step
Epoch 12/50
29/29 - 0s - loss: 0.6070 - accuracy: 0.7671 - 72ms/epoch - 2ms/step
Epoch 13/50
29/29 - 0s - loss: 0.59

In [19]:
# lets test it
model.metrics_names

['loss', 'accuracy']

In [20]:
# lets get our visualization tools 
from sklearn.metrics import confusion_matrix,classification_report

In [24]:
predictions = (model.predict(scaled_X_test) > 0.5).astype("int32")
# the right answer was the y_test
confusion_matrix(y_test, predictions)

array([[244,  13],
       [ 10, 186]], dtype=int64)

In [25]:
# what about precision 
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

         0.0       0.96      0.95      0.95       257
         1.0       0.93      0.95      0.94       196

    accuracy                           0.95       453
   macro avg       0.95      0.95      0.95       453
weighted avg       0.95      0.95      0.95       453



In [26]:
model.save('mysupermodel.h5')

In [28]:
from keras.models import load_model
newmodel = load_model('mysupermodel.h5')

In [31]:
type(newmodel)

keras.engine.sequential.Sequential